# Generated by Django 5.0.1 on 2025-07-15 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=128, unique=True)),
                ('thread_id', models.CharField(max_length=128)),
                ('subject', models.TextField()),
                ('body_plain', models.TextField()),
                ('body_html', models.TextField(blank=True, null=True)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('category', models.CharField(blank=True, choices=[('PROSPECT_SINGLE', 'Single Prospect'), ('JOB_LINK_LIST', 'Job Link List'), ('APPLICATION_RESPONSE', 'Application Response')], max_length=30, null=True)),
                ('sub_category', models.CharField(blank=True, choices=[('DENIAL', 'Denial'), ('INTERESTED', 'Interested')], max_length=20, null=True)),
                ('draft_id', models.CharField(blank=True, max_length=128, null=True)),
                ('has_to_respond_label', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='applications.application')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('fetched_html', models.TextField(blank=True, null=True)),
                ('fetched_text', models.TextField(blank=True, null=True)),
                ('is_valid_listing', models.BooleanField(default=False)),
                ('confidence_score', models.IntegerField(blank=True, null=True)),
                ('extracted_company', models.CharField(blank=True, max_length=128, null=True)),
                ('extracted_role', models.CharField(blank=True, max_length=128, null=True)),
                ('crawl_status', models.CharField(choices=[('PENDING', 'Pending'), ('FETCHED', 'Fetched'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_links', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_links', to=settings.AUTH_USER_MODEL)),
                ('source_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_links', to='gmail.email')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source_email', 'url')},
            },
        ),
    ]
